### ISSUE TITLE
Disable download and archiving of big datasets via the portal

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/projectbrowser-portlet#30]
We have observed that the taring of big files makes the portal unresponsive and affects all users trying to access their datasets.

The web-server should not be responsible to deal with this CPU, IO and network intensiv tasks, but only serve access to the projects and offers. Downloads of smaller datasets in the two to three digit Megabyte range should be uncritical though.

Suggestion:

Disable the multiple download of datasets with an individual dataset size of > 100Mb and an amount of > 50 files.

**Comment by wow-such-code** [comment]
Solved in 1.11.4
