### ISSUE TITLE
Wrong email address in error message "Unable to load project"

### ISSUE THREAD

**Issue by mGauder** [qbicsoftware/projectbrowser-portlet#5]
Hi all,

I just encountered that the error message "Unable to load project" displays the wrong support email address info@qbic.uni-tuebingen.de, which does not exist anymore. This might also be the case for other error messages..

Cheers,

Marie

 ![screenshot](https://user-images.githubusercontent.com/9446153/53176969-73eeda80-35ef-11e9-985d-9a0c50299922.png)

**Comment by chahuistle** [comment]
What is the right email address?

**Comment by christopher-mohr** [comment]
support@qbic.zendesk.com
